### ISSUE TITLE
Add zap fields and setting attribututes to trace in context

### ISSUE THREAD

**Issue by ianthpun** [uptrace/opentelemetry-go-extra#59]
we currently are following a pattern where we use `ctxzap` from `https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v1.3.0/logging/zap/ctxzap/context.go#L24-L30` where we are able to add additional zap fields into the context logger so that when the function starts/exits, the logger middleware will be able to run `Info` and have all the additional fields added alongside the function.

We want to be able to combine that functionality with what we have here with `otelzap` so that any call to a new `AddFields` functions will 
1) add the additional zapFields into `l.l.extrafields`(?)
2) run `span.SetAttributes` for those fields into the span tracer

Lemme know if this is something we can have otelzap support, or if im approaching this incorrectly.

**Comment by vmihailenco** [comment]
It depends on how general we can make it so it is useful for more than once person. Also see https://github.com/uptrace/opentelemetry-go-extra/pull/60

**Comment by togiles** [comment]
We are using open telemetry with datadog, and in order to connect our logs and traces we need to provide both a trace_id and a span_id using specific field names (i.e. `dd.trace_id` and `dd.span_id`).  See the following documentation for details:

https://docs.datadoghq.com/tracing/connect_logs_and_traces/opentelemetry/

Having an option to add arbitrary fields on zap logs would be really beneficial to tying these all together.  We can of course see the events in our traces, however would prefer leveraging the logs + trace connection within datadog directly if possible.

**Comment by tamj0rd2** [comment]
> It depends on how general we can make it so it is useful for more than once person

How about exposing the already existing `With` API? The otelzap sugared logger exposes it, but the logger in otelzap doesn't
